### ISSUE TITLE
nie mam dostępu do wysyłania zmian

### ISSUE THREAD

**Issue by maxsroka** [Inst-Edu-Tech-Inf/100Plus#3]
Nie mam dostępu do wysyłania zmian. Gdy próbuje stworzyć plik na githubie widzę taki komunikat: 
> You’re creating a file in a project you don’t have write access to.

A jak próbuje pushować (git push origin develop)
> remote: Permission to Inst-Edu-Tech-Inf/100Plus.git denied to pixldev.
fatal: unable to access 'https://github.com/Inst-Edu-Tech-Inf/100Plus/': The requested URL returned error: 403

@marcinkolacz

**Comment by marcinkolacz** [comment]
Mój błąd. Już naprawiłem. Wszyscy mają uprawnienia do zapisywania.

**Comment by marcinkolacz** [comment]
Naprawiłem. Zapomniałem ustawić prawa do zapisu :( Spróbuj coś wysłać.
Jakby nie wyszło pisz na maila lub na grupie
Pozdrawiam
Marcin Kołacz

Pt., 13 gru 2019, 20:56 użytkownik pixl <notifications@github.com> napisał:
