### ISSUE TITLE
Jak ma działać wykonywanie zadań?

### ISSUE THREAD

**Issue by maxsroka** [Inst-Edu-Tech-Inf/100Plus#4]
Nie wiem jak to ma działać, gracz ma klikać na karty na ręce które chce zsumować i potem kliknąć kartę zadania którą chce wykonać czy przeciągać odpowiednie karty z ręki na karty zadań czy jeszcze jakoś inaczej?
@marcinkolacz

**Comment by marcinkolacz** [comment]
Na prawo od karty zadań musi być pole, na które można przeciągnąć kartę z ręki. Gdy są tam już jakieś karty, kolejna powinna być dodawana jako ostatnia. Trzeba pamiętać, że później pod każdą kartę gracza będzie można przeciągnąć jeden power up. Potrzebny jest osobny przycisk akceptujący dodanie wszystkich kart. Zanim zostanie użyty każdą dołożoną kartę można wycofać, przeciągając ją.
