### ISSUE TITLE
Dostosowanie rozmiaru menu do okna Windows

### ISSUE THREAD

**Issue by marcinkolacz** [Inst-Edu-Tech-Inf/100Plus#5]
Przyciski Menu nie skalują się i nie rozmieszczają w zależności od rozmiaru okna w Windows

**Comment by maxsroka** [comment]
naprawione w https://github.com/Inst-Edu-Tech-Inf/100Plus/commit/474af6e58760a2706c10abb29c47c6ea51bdfd09
